"""
SpiderFoot API Client for IOC Enrichment.
Used in Phase 3 (Analysis).
"""
import os
import requests
import logging
import time
from dotenv import load_dotenv

load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class SpiderFootClient:
    def __init__(self):
        self.base_url = os.getenv("SPIDERFOOT_SERVER_URL", "http://127.0.0.1:5001").rstrip('/')
        self.api_key = os.getenv("SPIDERFOOT_API_KEY", "")
        
    def start_scan(self, scan_name: str, target: str, module_list: list = None) -> str:
        """
        Starts a new SpiderFoot scan against a specific target (IP, Domain, Email).
        Returns the unique Scan ID if successful.
        """
        endpoint = f"{self.base_url}/api/startscan"
        
        # Default modules for quick threat intel lookup if none specified
        if not module_list:
            module_list = ["sfp_abuseipdb", "sfp_virustotal", "sfp_shodan", "sfp_whois"]
            
        payload = {
            "scanname": scan_name,
            "scantarget": target,
            "modulelist": ",".join(module_list),
            "key": self.api_key
        }
        
        try:
            logging.info(f"Sending scan request to SpiderFoot for target: {target}")
            response = requests.post(endpoint, data=payload, timeout=15)
            
            if response.status_code == 200:
                result = response.json()
                if result[0] == "SUCCESS":
                    scan_id = result[1]
                    logging.info(f"Scan started successfully. Scan ID: {scan_id}")
                    return scan_id
                else:
                    logging.error(f"SpiderFoot error: {result[1]}")
            else:
                logging.error(f"HTTP error from SpiderFoot server: {response.status_code}")
        except Exception as e:
            logging.error(f"Failed to connect to SpiderFoot server: {str(e)}")
            
        return ""

    def get_scan_status(self, scan_id: str) -> str:
        """
        Checks the status of an ongoing scan (RUNNING, FINISHED, etc.).
        """
        endpoint = f"{self.base_url}/api/scanstatus"
        params = {"id": scan_id, "key": self.api_key}
        
        try:
            response = requests.get(endpoint, params=params, timeout=10)
            if response.status_code == 200:
                # Returns status string like 'RUNNING', 'FINISHED'
                return response.json()[1]
        except Exception as e:
            logging.error(f"Error checking scan status for {scan_id}: {str(e)}")
        return "UNKNOWN"

    def get_scan_results(self, scan_id: str) -> list:
        """
        Fetches the structural OSINT data generated by the completed scan.
        """
        endpoint = f"{self.base_url}/api/scanresults"
        params = {"id": scan_id, "key": self.api_key}
        
        try:
            response = requests.get(endpoint, params=params, timeout=15)
            if response.status_code == 200:
                return response.json()  # Returns raw data elements
        except Exception as e:
            logging.error(f"Error fetching results for scan {scan_id}: {str(e)}")
        return []

# Test execution block
if __name__ == "__main__":
    print("=== TESTING SPIDERFOOT CLIENT ===")
    client = SpiderFootClient()
    
    # Example: Scanning a suspicious infrastructure domain
    test_scan_id = client.start_scan("CTI_Pipeline_Test", "example-malicious-domain.com")
    
    if test_scan_id:
        print(f"Tracking Scan ID: {test_scan_id}")
        # In a real pipeline, you would loop or wait until status is 'FINISHED'
        status = client.get_scan_status(test_scan_id)
        print(f"Current Scan Status: {status}")