"""
SpiderFoot API Client for IOC Enrichment.
Used in Phase 3 (Analysis).
"""
import os
import requests
import logging
import time
import json
from dotenv import load_dotenv

load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class SpiderFootClient:
    def __init__(self):
        self.base_url = os.getenv("SPIDERFOOT_SERVER_URL", "http://127.0.0.1:5001").rstrip('/')
        self.api_key = os.getenv("SPIDERFOOT_API_KEY", "")
        
    def start_scan(self, scan_name: str, target: str, module_list: list = None) -> str:
        """Starts a new SpiderFoot scan against a specific target."""
        endpoint = f"{self.base_url}/api/startscan"
        if not module_list:
            module_list = ["sfp_abuseipdb", "sfp_virustotal", "sfp_shodan", "sfp_whois"]
            
        payload = {
            "scanname": scan_name,
            "scantarget": target,
            "modulelist": ",".join(module_list),
            "key": self.api_key
        }
        
        try:
            response = requests.post(endpoint, data=payload, timeout=15)
            if response.status_code == 200:
                result = response.json()
                if result[0] == "SUCCESS":
                    return result[1] # Returns scan_id
        except Exception as e:
            logging.error(f"Failed to connect to SpiderFoot server: {str(e)}")
        return ""

    def get_scan_status(self, scan_id: str) -> str:
        """Checks the status of an ongoing scan (RUNNING, FINISHED, etc.)."""
        endpoint = f"{self.base_url}/api/scanstatus"
        params = {"id": scan_id, "key": self.api_key}
        try:
            response = requests.get(endpoint, params=params, timeout=10)
            if response.status_code == 200:
                return response.json()[1]
        except Exception as e:
            logging.error(f"Error checking scan status: {str(e)}")
        return "UNKNOWN"

    def get_scan_results(self, scan_id: str) -> list:
        """Fetches the structural OSINT data generated by the completed scan."""
        endpoint = f"{self.base_url}/api/scanresults"
        params = {"id": scan_id, "key": self.api_key}
        try:
            response = requests.get(endpoint, params=params, timeout=15)
            if response.status_code == 200:
                return response.json()
        except Exception:
            pass
        return []

# ==============================================================================
# BỘ ADAPTER DÀNH CHO PIPELINE (GỌI TỪ RUN_ANALYSIS.PY)
# ==============================================================================

def quick_osint_scan(target_ioc: str, use_mock=True) -> dict:
    """
    Hàm bọc API Client để trinh sát IP/Domain.
    - use_mock=True: Trả về kết quả ngay lập tức (Dành cho Demo/Bảo vệ đồ án).
    - use_mock=False: Gọi SpiderFoot thật, đợi tối đa 60s rồi lấy kết quả.
    """
    logging.info(f"[~] OSINT Module đang trinh sát mục tiêu: {target_ioc}...")
    
    if use_mock:
        # Trả về dữ liệu giả lập ngay lập tức để không làm nghẽn Pipeline AI
        time.sleep(1) # Giả lập độ trễ mạng
        return {
            "target": target_ioc,
            "risk_score": "High",
            "associated_threats": ["Ransomware C2", "CobaltStrike Beacon"],
            "malicious_votes_virustotal": 18,
            "shodan_ports": [80, 443, 8080],
            "note": "OSINT Data provided by SpiderFoot Pipeline"
        }
    
    # --- LUỒNG CHẠY THẬT (PRODUCTION) ---
    client = SpiderFootClient()
    scan_name = f"AutoCTI_{target_ioc}_{int(time.time())}"
    
    scan_id = client.start_scan(scan_name, target_ioc)
    if not scan_id:
        return {"error": "Không thể khởi động SpiderFoot scan."}
    
    # Đợi tối đa 60 giây (Chỉ quét các module nhanh)
    max_wait_time = 60
    waited = 0
    while waited < max_wait_time:
        status = client.get_scan_status(scan_id)
        if status in ["FINISHED", "ABORTED"]:
            break
        time.sleep(10)
        waited += 10
        logging.info(f"   ... Đang chờ OSINT Scan ({waited}s / {max_wait_time}s)")
        
    # Lấy kết quả thô
    raw_results = client.get_scan_results(scan_id)
    
    # Trích xuất gọn gàng lại cho AI dễ đọc (Tránh JSON quá to làm AI bị "ảo giác")
    summary = {
        "target": target_ioc,
        "total_data_points_found": len(raw_results),
        "status": "partial_scan" if waited >= max_wait_time else "completed"
    }
    return summary